### ISSUE TITLE
[Maintenance] Pin OpenJDK runtime images

### ISSUE THREAD

**Issue by devtobi** [it-at-m/refarch#115]
### Relevant component

refarch-gateway, refarch-integrations

### Problem description (optional)

Runtime images are currently using `latest` tag with pinned SHA (for security reasons). However version bumps suggested by renovate are not transparent in that way.

### Desired solution

Use specific version tags

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hupling** [comment]
Im Prinzip eine gute Idee, aber es gibt Projekte die werden einmal im Jahr ausgerollt. Daher finde ich es besser, wenn man es auf "latest" lässt. Es gibt noch genügend Projekte mit uralt Dependencies
