### ISSUE TITLE
[Bug] The refarch-s3-integration-rest-client-starter always call http://localhost:8086

### ISSUE THREAD

**Issue by boal** [it-at-m/refarch#146]
### Bug description

The Lib `refarch-s3-integration-rest-client-starter` is sending all requests against the url `http://localhost:8086`, despite the property `refarch.s3.client.document-storage-url` ist set to another url.

Reason for this behaviour:

The `de.muenchen.refarch.integration.s3.client.ApiClient` is created as a Bean in class `de.muenchen.refarch.integration.s3.client.configuration.S3IntegrationClientAutoConfiguration` without defining the `ApiClient.basePath` with the value of the property `refarch.s3.client.document-storage-url`.

![image](https://github.com/user-attachments/assets/c28a38fc-ac43-4a3e-ba94-96af0e9cf215)

The default value of the `ApiClient.basePath` is `http://localhost:8086`.

![image](https://github.com/user-attachments/assets/38e55484-84b7-492b-991c-5453cac6e3c5)

### Expected behaviour

The Lib `refarch-s3-integration-rest-client-starter` should make all requests against the url defined in `refarch.s3.client.document-storage-url`.

### Steps for reproduction

n/a

### Affected version

1.0.0

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by simonhir** [comment]
Should be fixed with release 1.0.1
@boal would be nice if you can give appropriate feedback

**Comment by boal** [comment]
Thank you! The url is not set correctly.
