### ISSUE TITLE
[Maintenance] Stack update: Add configuration for pgAdmin automatic db connection

### ISSUE THREAD

**Issue by devtobi** [it-at-m/refarch#166]
### Problem description (optional)

See https://github.com/it-at-m/refarch-templates/issues/323

### Desired solution

https://github.com/it-at-m/refarch-templates/pull/324

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by simonhir** [comment]
Doesn't contain pgAdmin as not synced with refarch-tempaltes anymore.
