### ISSUE TITLE
[Maintenance] Stack sync: Add AppSwitcher

### ISSUE THREAD

**Issue by devtobi** [it-at-m/refarch#167]
### Problem description (optional)

See https://github.com/it-at-m/refarch-templates/issues/100

### Desired solution

See https://github.com/it-at-m/refarch-templates/pull/308

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devtobi** [comment]
@simonhir Do you think we should add this to here? Technically AppSwitcher is not required for development of gateway, integrations, etc. so we could leave it out here and only include it in the stack of https://github.com/it-at-m/refarch-templates.
However it might also be valid to merge because of trying to keep both in sync as good as possible.

**Comment by simonhir** [comment]
I thought we already broke the sync and just transfer what is needed.
So i wouldn't copy it over.

**Comment by devtobi** [comment]
> I thought we already broke the sync and just transfer what is needed. So i wouldn't copy it over.

Ok thats fine for me, closing the issue as not planned.
