### ISSUE TITLE
Remove unused code

### ISSUE THREAD

**Issue by hupling** [it-at-m/refarch#177]
https://github.com/it-at-m/refarch/blob/35c3ea676fb32be1d3245c19ff9c3f9d3a194f02/refarch-gateway/src/main/resources/application-local.yml#L15

hier steht noch was mit DigiWf drin

**Comment by devtobi** [comment]
This might not just be maintenance issue, but a bug. I guess the RewritePath has to match the Path Predicate. @simonhir What do you think about this?
