### ISSUE TITLE
[Bug] refarchgateway profile json logging is not working

### ISSUE THREAD

**Issue by hupling** [it-at-m/refarch#178]
### Bug description

 refarchgateway profile json logging is not working https://github.com/it-at-m/refarch/tree/main/refarch-gateway#profiles I still don't get json output

### Expected behaviour

json output

### Steps for reproduction

SPRING_PROFILES_ACTIVE json-logging

### Affected version

1.0.0

### Affected component

refarch-gateway

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devtobi** [comment]
This is not a bug, JSON Logging is currently not yet implemented for API Gateway and Integration Services. See https://github.com/it-at-m/refarch/issues/140.

**Comment by devtobi** [comment]
Sorry, I misinterpreted the information. JSON Logging is already part of the current gateway. So I am reopening this issue. Still #140 might solve the problem. @simonhir What do you think about this?

**Comment by devtobi** [comment]
I just double checked and in gateway version `1.0.0` the profile for logging was still named `json-logger`. Please update to latest gateway image to make `json-logging` profile work for you. ;)

**Comment by simonhir** [comment]
Can't that be closed then?

**Comment by devtobi** [comment]
> Can't that be closed then?

We didn't get any response from the issue author so I'd say "yes" 😀

**Comment by hupling** [comment]
![grafik](https://github.com/user-attachments/assets/dda5e396-7f55-4e46-9f4a-8df903f3320c)

geht
