### ISSUE TITLE
[Bug] in Version der aktuellen Version startet nicht, wenn man keine Truststore gesetzt hat. 

### ISSUE THREAD

**Issue by hupling** [it-at-m/refarch#180]
### Bug description

 in Version der aktuellen Version startet nicht, wenn man keine Truststore gesetzt hat. Das ist wichtig, wenn man eine Anwendung mit no Security hat

Bei Version 1.0.0 hat es noch funktioniert

### Expected behaviour

auch ohne Truststore startet das Gateway

### Steps for reproduction

Anwendung starten

### Affected version

aktuelle

### Affected component

refarch-gateway

### Last working version (optional)

1.0.0

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devtobi** [comment]
@simonhir Could you investigate this? Gateway not starting is a critical bug.

**Comment by hupling** [comment]
Vielleicht hängt das auch damit zusammen https://github.com/it-at-m/refarch/issues/193#issuecomment-2387720220

**Comment by hupling** [comment]
![grafik](https://github.com/user-attachments/assets/2ae449d1-076b-4aed-8401-39ef90d30d66)

hier nochmal die Fehler meldung

@simonhir

**Comment by simonhir** [comment]
Not a bug.
You seem to define the `SSO_ISSUER_URL` which then connects to the sso and requires the truststore.

That the `SSO_ISSUE_URL` is wrongly required for `no-security` will be fixed within #193
