### ISSUE TITLE
Remove logout endpoint

### ISSUE THREAD

**Issue by devtobi** [it-at-m/refarch#24]
**Is your feature request related to a problem? Please describe.**
The logout functionality of the gateway is no longer needed, because the web application frontends themself do not provide a logout functionality anymore. On top of that our web application sessions are solely managed by the IDP and support SSO. Thus a logout is not needed anymore

**Describe the solution you'd like**
Remove all logic related to the logout endpoint (including the logout.html file)

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by simonhir** [comment]
@devtobi wouldn't it be better to implement a correct logout, which also destroys the sso session. Think that would be useful for testing when using test users instead the automatic sso login.

**Comment by simonhir** [comment]
Found following documentation for oidc logout: https://docs.spring.io/spring-security/reference/reactive/oauth2/login/logout.html
Tried a bit around but didn't work as intended or more doesn't provide any advantage, so i will remove the logout functionality as suggested.
