### ISSUE TITLE
TraceId and SpanId not shown in log

### ISSUE THREAD

**Issue by devtobi** [it-at-m/refarch#25]
**Is your feature request related to a problem? Please describe.**
TraceId and SpanId are not shown in log output.

**Describe the solution you'd like**
TraceId and SpanId should be logged in the output

**Solution**
`Hooks.enableAutomaticContextPropagation();` has to be called
See https://medium.com/@aakashkumar2001jha/mastering-reactive-tracing-in-spring-boot-3-a-comprehensive-guide-to-achieving-seamless-29c1229177ca for a more detailed example.
It might be necessary to add additional dependencies and bean implementations (see provided link)

**Describe alternatives you've considered**

**Additional context**
Take a further look into https://medium.com/@aakashkumar2001jha/mastering-reactive-tracing-in-spring-boot-3-a-comprehensive-guide-to-achieving-seamless-29c1229177ca for more sophisticated setup.
- Internal issue: https://git.muenchen.de/ccse/refarch-archetype/refarch-archetype-apigateway/-/issues/118

**Comment by simonhir** [comment]
Propagation between services need to be configured explicitly see https://docs.spring.io/spring-boot/reference/actuator/tracing.html#actuator.micrometer-tracing.propagating-traces
