### ISSUE TITLE
doku spring-cloud-gateway

### ISSUE THREAD

**Issue by klml** [it-at-m/refarch#47]
This project is based on [spring-cloud-gateway](https://spring.io/projects/spring-cloud-gateway) please add this in Readme.md

And describe the extension this project brings to spring-cloud-gateway (filters etc)

Mention this project on https://opensource.muenchen.de/software/spring.html

**Comment by simonhir** [comment]
@klml could this be closed, as you referenced the complete repo on opensource.muenchen.de?

**Comment by klml** [comment]
done with https://github.com/it-at-m/refarch/pull/207
