### ISSUE TITLE
Dev stack

### ISSUE THREAD

**Issue by simonhir** [it-at-m/refarch#56]
**Description**
For local development a stack is needed see https://github.com/it-at-m/refarch-templates/tree/main/stack.
It need to be thought about if a duplication of the refarch-template stack is necessary or an alternative is available.
On copy support for integrations need to be added and not needed services like postgresql should be removed.

**Comment by devtobi** [comment]
Maybe https://docs.docker.com/compose/multiple-compose-files/extends/ might be suitable?

**Comment by simonhir** [comment]
Also thought about git submodule but isn't working as only whole repositories can be "mounted".
